-- PG Migration 0023 — Lookups del Plan de Cargas (fuentes de los desplegables).
--
-- Tablas de referencia para autocompletar el form de Plan de Cargas:
--   chofer (nombre+celular), productor (nombre+iniciales), transportista,
--   frontera, carpeta_import (control de carpetas). chofer y carpeta_import se
--   cargan con app/scripts/import_choferes.py y import_carpetas.py (grandes).
--   Las 3 chicas (productor/transportista/frontera) se siembran acá.

CREATE TABLE IF NOT EXISTS ext.chofer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    celular VARCHAR(40) NULL
);

CREATE TABLE IF NOT EXISTS ext.productor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    iniciales VARCHAR(10) NULL
);

CREATE TABLE IF NOT EXISTS ext.transportista (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ext.frontera (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ext.carpeta_import (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NULL,
    factura VARCHAR(40) NULL,
    carpeta VARCHAR(40) NULL,
    exportador VARCHAR(150) NULL,
    frontera VARCHAR(60) NULL,
    transportista VARCHAR(100) NULL,
    cantidad INT NULL,
    cargado INT NULL,
    saldo INT NULL,
    afidi VARCHAR(300) NULL,
    dua VARCHAR(40) NULL
);
CREATE INDEX IF NOT EXISTS ix_carpeta_import_carpeta ON ext.carpeta_import(carpeta);

INSERT INTO ext.productor (nombre, iniciales) VALUES
    ('Ulgo', 'HG'),
    ('Exoticos PY', NULL),
    ('Claudia', 'CH'),
    ('Gilson', 'GT'),
    ('Jaime', 'JM'),
    ('Papa', 'PA'),
    ('Boniato', 'BO'),
    ('Sidnei', 'SR'),
    ('Benini', 'BN'),
    ('Valdemar', 'VH'),
    ('Valdemar Ita', 'VA'),
    ('Adriano', 'AD'),
    ('Varios', 'VA'),
    ('Nordeste', 'ND'),
    ('Corupá', 'CP'),
    ('Jhony Viera', 'JV'),
    ('Muller', 'MU'),
    ('Sergio', 'SG'),
    ('Vitor', 'VM'),
    ('Marconi Kons', 'MK'),
    ('Ivo Zimerman', 'IZ'),
    ('Banana MG', 'MG'),
    ('A Confirmar', NULL),
    ('Paraguay', 'PY'),
    ('Paraguay EC', 'PYE'),
    ('Paraguay OP', 'PYO'),
    ('Paraguay MS', 'PYM'),
    ('Paraguay GM', 'GM'),
    ('Paraguay DF', 'DF'),
    ('Jorge Marangoni', 'JM'),
    ('Paraguay HF', 'HF'),
    ('Paraguay SF', 'SF'),
    ('Bolivia Tuli', 'BT'),
    ('João Claudio Winter', 'JW'),
    ('Osnildo Stein', 'ST'),
    ('Zapellini', 'ZP'),
    ('Fischer', 'FH'),
    ('Tureck', 'TK'),
    ('Chicolandia', NULL),
    ('Josemar Provesi', 'JP'),
    ('Cebolla', 'CE'),
    ('Abacaxi', 'AB'),
    ('AgroBianvirc', 'BRSP'),
    ('Cobalchini', 'CB'),
    ('Junkes', 'JS'),
    ('Wagner Schveitzer', 'WC'),
    ('Banana Combinada', NULL),
    ('BAHIA', 'BA'),
    ('Banana SP', 'BRSP'),
    ('Bahia + Exoticos', 'BA'),
    ('Marnei Meurer', 'MM'),
    ('Cassio Hauck', NULL),
    ('Aldo Corupa', 'AC'),
    ('Alexandre Wilbert', 'AW'),
    ('Vinicios Bonkoski', 'VB'),
    ('Furlani', 'FU'),
    ('Airton Curuca', NULL)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO ext.transportista (nombre) VALUES
    ('CMCN'),
    ('Amaro'),
    ('Balbiani'),
    ('Cigliuti'),
    ('Cordenonsi'),
    ('El Palomar'),
    ('Pradera'),
    ('Transzanini'),
    ('Gral'),
    ('Aotrans'),
    ('Sergio Nava'),
    ('Marvel'),
    ('K2'),
    ('Costa Rica'),
    ('Schwanck'),
    ('Silvio'),
    ('Tottal Brasil'),
    ('Trans America'),
    ('Transitex'),
    ('Ruiz'),
    ('Viana'),
    ('Realeza'),
    ('Azzolini'),
    ('VI-MA'),
    ('Coopecarga'),
    ('Chabat'),
    ('Transporte Carneiro')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO ext.frontera (nombre) VALUES
    ('Montevideo'),
    ('Salto'),
    ('Chuy'),
    ('Río Branco'),
    ('Rivera')
ON CONFLICT (nombre) DO NOTHING;
