-- PG Migration 0040 — Cámara(s) de ingreso en el Pie de Camión.
--
-- A qué cámara de maduración entró la fruta del camión. Ubicación ZAC (30 cámaras)
-- o CR (13 cámaras) + número. Normalmente TODA la fruta entra a UNA cámara entera;
-- por eso el caso típico es una sola fila con cantidad NULL (= todas las cajas del
-- camión). Pero se puede REPARTIR en varias cámaras → varias filas, cada una con su
-- cantidad de cajas. Tabla hija como líneas/productos/fotos.

CREATE TABLE IF NOT EXISTS ext.pie_de_camion_camara (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pie_camion_id INT NOT NULL,
    ubicacion VARCHAR(3) NOT NULL,          -- 'ZAC' | 'CR'
    numero SMALLINT NOT NULL,               -- 1-30 (ZAC) / 1-13 (CR)
    cantidad INT NULL,                      -- cajas en esta cámara (NULL = todas, caso 1-cámara)
    orden INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pie_de_camion_camara_pie
        FOREIGN KEY (pie_camion_id) REFERENCES ext.pie_de_camion(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_camara_pie ON ext.pie_de_camion_camara(pie_camion_id);
