-- PG Migration 0046 — Alias de productos GDU (Grupo Disco) → artículos Aloha.
--
-- Los pedidos de GDU llegan en PDF (reporte OLisPedCenVeg) con SUS códigos y
-- descripciones de producto. Al importar el PDF, Aloha matchea cada línea por
-- gdu_codigo contra esta tabla; lo que no matchea lo resuelve la persona en la
-- pantalla de revisión (elige el artículo Aloha) y la elección se guarda acá →
-- el matcheo mejora solo con el uso.
--
-- Sembrada con los 11 mapeos validados contra los pedidos reales del 07/07/2026
-- (los 3 PDFs de ese día suman EXACTO el pedido GDU #14, en bultos).

CREATE TABLE IF NOT EXISTS ext.gdu_producto_alias (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gdu_codigo VARCHAR(20) NOT NULL,          -- código del producto en el PDF (ej. 414103)
    gdu_descripcion VARCHAR(200) NOT NULL,    -- última descripción vista en el PDF
    cod_art VARCHAR(30) NOT NULL,             -- artículo Aloha/Macrosoft (o 'AX<n>' interno)
    descripcion VARCHAR(200) NOT NULL,        -- descripción Aloha (snapshot para display)
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
    actualizado_por_usuario_id INT NULL,
    CONSTRAINT uq_gdu_producto_alias_codigo UNIQUE (gdu_codigo)
);

INSERT INTO ext.gdu_producto_alias (gdu_codigo, gdu_descripcion, cod_art, descripcion) VALUES
    ('414102', 'BANANA BRASIL OFERTA',            '010101',  'Banana Brasil (super)'),
    ('414103', 'BANANA ECUADOR',                  '010701',  'Banana Ecuador (Super)'),
    ('400311', 'PALTA HASS CALIBRE GRANDE',       '600101',  'Palta Brasil Cal. 60'),
    ('430006', 'ARANDANO IMPORTADO PETACA 125 G.','890202',  'Arandanos (Super)'),
    ('414118', 'KIWI IMPORTADO',                  '0802272', 'Kiwi  (Super)'),
    ('414141', 'SANDIA IMPORTADA',                '981002',  'Sandia (Super)'),
    ('414227', 'LIMON TAHITI',                    '150102',  'Lima (Super)'),
    ('400607', 'PLATANO',                         '760702',  'Platano Ecuador (Super)'),
    ('407567', 'CHOCLO IMPORTADO BANDEJA X2',     '030103',  'Choclo importado x 2 (Super)'),
    ('400224', 'JENGIBRE',                        '090902',  'Jengibre (Super)'),
    ('404692', 'CURCUMA FRESCA KG',               '090905',  'Cúrcuma Br  5k  (Súper)'),
    -- 13/07: PDFs gdu4/gdu5 vs pedido GDU #20 real (30 bultos exactos)
    ('400235', 'PIÑA',                            '120401',  'Piña (Super)')
ON CONFLICT (gdu_codigo) DO NOTHING;
