-- PG Migration 0048 — Módulo VENTA (reemplazo del "Tomador de pedidos" de Macrosoft).
--
-- Aloha crea pedidos (Cabezal2/Lineas2, Documento='30') directamente en Macrosoft,
-- indistinguibles de los del tomador → caja los factura sin enterarse. Contrato
-- completo relevado y verificado el 14/07 (memoria reference_tomador_pedidos_macrosoft).
--
-- Metadata Aloha (ext.*) + columnas nuevas del espejo. Las columnas de
-- legacy.cabezal2 también las agrega el self-heal de pg_mirror_sync, pero van
-- acá igual (guardadas por IF EXISTS): si el daemon no llegó a bootstrapear,
-- el listado de Venta las referencia y daría UndefinedColumn.

DO $$
BEGIN
    IF to_regclass('legacy.cabezal2') IS NOT NULL THEN
        ALTER TABLE legacy.cabezal2 ADD COLUMN IF NOT EXISTS totaldebe NUMERIC(15,4);
        ALTER TABLE legacy.cabezal2 ADD COLUMN IF NOT EXISTS encuotas SMALLINT;
        ALTER TABLE legacy.cabezal2 ADD COLUMN IF NOT EXISTS consumofinal SMALLINT;
    END IF;
END $$;

-- Mapeo usuario Aloha → código de vendedor de Macrosoft (tabla Vendedores: 1=Matias,
-- 2=Maxi, 3=Renzo, 4=Christian, 5=Catriel, 6=Andres, 7=Facundo). Lo administra el
-- submódulo "Vendedores" de Venta. Sin fila acá, el usuario no puede crear pedidos.
CREATE TABLE IF NOT EXISTS ext.venta_vendedor (
    usuario_id INT PRIMARY KEY,
    vendedor SMALLINT NOT NULL,
    actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
    actualizado_por_usuario_id INT NULL,
    CONSTRAINT fk_venta_vendedor_usuario
        FOREIGN KEY (usuario_id) REFERENCES ext.usuarios(id) ON DELETE CASCADE
);

-- Un registro por pedido creado DESDE ALOHA (los del tomador viejo no están acá).
-- Da el "Mis pedidos" (por usuario Aloha) y la auditoría de anulación.
-- nro_fact = Cabezal2.NROFACT (único global en Macrosoft para doc '30').
CREATE TABLE IF NOT EXISTS ext.venta_pedido_meta (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro_fact INT NOT NULL,
    nro_doc VARCHAR(20) NOT NULL,
    usuario_id INT NOT NULL,
    vendedor SMALLINT NOT NULL,
    cliente_cod INT NOT NULL,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    anulado_en TIMESTAMP NULL,
    anulado_por_usuario_id INT NULL,
    CONSTRAINT uq_venta_pedido_meta_nrofact UNIQUE (nro_fact),
    CONSTRAINT fk_venta_pedido_meta_usuario
        FOREIGN KEY (usuario_id) REFERENCES ext.usuarios(id)
);
CREATE INDEX IF NOT EXISTS ix_venta_pedido_meta_usuario ON ext.venta_pedido_meta(usuario_id);
CREATE INDEX IF NOT EXISTS ix_venta_pedido_meta_cliente ON ext.venta_pedido_meta(cliente_cod);

-- Idempotencia del POST de pedidos: la tablet manda un `ref` (UUID) por intento
-- de envío. Se RESERVA acá ANTES de escribir en Macrosoft; al commitear se le
-- setea el nro_fact. Si el wifi se corta después del commit y el vendedor
-- reintenta con el mismo ref → devolvemos el pedido ya creado en vez de
-- duplicarlo en la cola de caja.
CREATE TABLE IF NOT EXISTS ext.venta_envio (
    ref UUID PRIMARY KEY,
    usuario_id INT NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    nro_fact INT NULL,
    nro_doc VARCHAR(20) NULL,
    total NUMERIC(12,2) NULL,
    CONSTRAINT fk_venta_envio_usuario
        FOREIGN KEY (usuario_id) REFERENCES ext.usuarios(id)
);
