-- Pedidos AGREGADOS (feature 28/07): el cliente "agrega" productos después de
-- su pedido original. Si el original YA salió de caja, el agregado se crea como
-- un pedido '30' NUEVO (flujo normal para Macrosoft) pero queda ENCADENADO al
-- original acá — Expedición/asignador/armador/teles muestran el vínculo.
--
-- Regla: el encadenado apunta SIEMPRE al pedido RAÍZ (agregar sobre un agregado
-- re-apunta a la raíz) → un solo grupo por cliente-día, fácil de razonar.
CREATE TABLE IF NOT EXISTS ext.pedido_agregado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento CHAR(4) NOT NULL DEFAULT '30  ',
    nro_fact INT NOT NULL,             -- el pedido AGREGADO (el nuevo)
    nro_fact_original INT NOT NULL,    -- el pedido RAÍZ al que se encadena
    creado_por INT NULL,               -- usuario Aloha que lo creó (venta)
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Un pedido es agregado de UN solo original (la raíz puede tener varios).
CREATE UNIQUE INDEX IF NOT EXISTS ux_pedido_agregado_nf
    ON ext.pedido_agregado (documento, nro_fact);
CREATE INDEX IF NOT EXISTS ix_pedido_agregado_original
    ON ext.pedido_agregado (documento, nro_fact_original);

-- Auditoría del caso "el pedido SIGUE en caja": se le agregan líneas al MISMO
-- pedido '30' en Macrosoft (contrato nativo verificado 28/07: solo INSERT de
-- Lineas2 copiando NroDoc/Fecha/Deposito, SIN tocar el cabezal — así lo hace
-- el tomador viejo a diario y caja factura recalculando desde las líneas).
-- Esta tabla deja rastro de quién agregó qué y cuándo (Macrosoft no lo registra).
CREATE TABLE IF NOT EXISTS ext.venta_linea_agregada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento CHAR(4) NOT NULL DEFAULT '30  ',
    nro_fact INT NOT NULL,
    usuario_id INT NULL,
    detalle TEXT NOT NULL,             -- resumen legible: "40× Banana ($750) · 10× Kiwi ($1.700)"
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_venta_linea_agregada_nf
    ON ext.venta_linea_agregada (documento, nro_fact);
