-- Código de importador impreso en las etiquetas Zebra, asociado AL CAMIÓN.
--
-- Problema: el código se tipea DOS veces — en la PC para imprimir las etiquetas
-- del pallet, y de nuevo en el celular al cargar el pie de camión. Cuando no
-- coinciden, el QR de la etiqueta apunta a un código que el pie no tiene.
-- Ahora el que imprime queda registrado acá y el celular lo pre-carga solo.
--
-- La clave es (placa, fecha) y NO la carga del Plan: el puente de OneDrive
-- borra y re-inserta TODA la tabla ext.plan_de_cargas cada 30s (y sin la
-- columna `id`, así que hasta el id de la carga cambia). placa+fecha es lo
-- mismo que ya identifica al camión en el QR de la etiqueta (CÓDIGO|PLACA|FECHA).
CREATE TABLE IF NOT EXISTS ext.etiqueta_camion (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa         VARCHAR(20) NOT NULL,        -- normalizada UPPER(BTRIM())
    fecha         DATE        NOT NULL,        -- fecha de DESCARGA (la del pie)
    codigo        VARCHAR(30) NOT NULL,        -- código de importador impreso
    cantidad      INT         NULL,            -- cuántas etiquetas salieron
    -- Best-effort, sólo informativo: el id de la carga puede haber cambiado en
    -- el próximo sync del puente. NO se usa para buscar.
    plan_carga_id INT         NULL,
    usuario_id    INT         NULL REFERENCES ext.usuarios(id) ON DELETE SET NULL,
    impreso_en    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Un camión no trae dos códigos distintos el mismo día: la última impresión
-- pisa a la anterior (upsert). Si se re-imprime con otro código, vale el último
-- — es el papel que quedó pegado en los pallets.
CREATE UNIQUE INDEX IF NOT EXISTS etiqueta_camion_placa_fecha_uq
    ON ext.etiqueta_camion (placa, fecha);
