-- PG Migration 0083 - Stock dashboard: precision y mapeo explicito.
--
-- Reemplaza el cruce posicional del Excel por identidades estables. Cada fila
-- visible del dashboard tiene reglas declarativas contra Macrosoft. Las reglas
-- mas especificas tienen menor prioridad y ganan antes que una familia
-- CodStock completa (casos Palta y Uva).

ALTER TABLE ext.inventario_stock_snapshot
    ALTER COLUMN stock TYPE NUMERIC(18,3)
    USING stock::NUMERIC(18,3);

CREATE TABLE IF NOT EXISTS ext.stock_dashboard_producto (
    clave VARCHAR(60) PRIMARY KEY,
    codigo_representativo VARCHAR(30) NOT NULL,
    etiqueta VARCHAR(100) NOT NULL,
    orden INT NOT NULL,
    tolerancia NUMERIC(18,3) NOT NULL DEFAULT 0,
    unidad VARCHAR(20) NOT NULL DEFAULT 'cajas',
    activo BOOLEAN NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_stock_dashboard_producto_orden UNIQUE (orden),
    CONSTRAINT ck_stock_dashboard_producto_clave CHECK (BTRIM(clave) <> ''),
    CONSTRAINT ck_stock_dashboard_producto_codigo CHECK (BTRIM(codigo_representativo) <> ''),
    CONSTRAINT ck_stock_dashboard_producto_etiqueta CHECK (BTRIM(etiqueta) <> ''),
    CONSTRAINT ck_stock_dashboard_producto_tolerancia CHECK (tolerancia >= 0)
);

CREATE TABLE IF NOT EXISTS ext.stock_dashboard_producto_regla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_clave VARCHAR(60) NOT NULL
        REFERENCES ext.stock_dashboard_producto(clave) ON DELETE CASCADE,
    tipo VARCHAR(30) NOT NULL,
    valor VARCHAR(200) NOT NULL,
    prioridad INT NOT NULL DEFAULT 100,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_stock_dashboard_regla UNIQUE (producto_clave, tipo, valor),
    CONSTRAINT ck_stock_dashboard_regla_tipo
        CHECK (tipo IN ('cod_stock', 'cod_art', 'cod_art_prefijo', 'descripcion_regex')),
    CONSTRAINT ck_stock_dashboard_regla_valor CHECK (BTRIM(valor) <> ''),
    CONSTRAINT ck_stock_dashboard_regla_prioridad CHECK (prioridad >= 0)
);

CREATE INDEX IF NOT EXISTS ix_stock_dashboard_regla_prioridad
    ON ext.stock_dashboard_producto_regla (prioridad, id);

-- Corte global del mismo consolidado que usa el informe de Macrosoft. El
-- primer inventario ciclico completo que se abre para una fecha lo congela;
-- los ciclos de Puesto, ZAC y CR de ese dia comparten exactamente esa foto.
-- No se usa el desglose por deposito para la comparacion: los pases internos
-- de Macrosoft solo cierran correctamente al consolidar todos los depositos.
CREATE TABLE IF NOT EXISTS ext.stock_dashboard_corte (
    fecha_control DATE PRIMARY KEY,
    fuente_actualizada_en TIMESTAMPTZ NULL,
    creado_por_usuario_id INT NULL REFERENCES ext.usuarios(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ext.stock_dashboard_corte_linea (
    fecha_control DATE NOT NULL
        REFERENCES ext.stock_dashboard_corte(fecha_control) ON DELETE CASCADE,
    cod_art VARCHAR(30) NOT NULL,
    descripcion VARCHAR(200) NULL,
    cod_stock VARCHAR(30) NULL,
    familia VARCHAR(120) NULL,
    pais VARCHAR(60) NULL,
    es_super BOOLEAN NOT NULL DEFAULT false,
    stock NUMERIC(18,3) NOT NULL DEFAULT 0,
    PRIMARY KEY (fecha_control, cod_art)
);

CREATE INDEX IF NOT EXISTS ix_stock_dashboard_corte_linea_cod_art
    ON ext.stock_dashboard_corte_linea (cod_art);

-- La planilla separaba 48 y 50 en el conteo, pero el reporte auxiliar de
-- Macrosoft los totaliza juntos. Compararlos como dos filas distintas duplica
-- o asigna mal el sistema; se conserva el detalle por CodArticulo en el drill.
DELETE FROM ext.stock_dashboard_producto_regla
WHERE producto_clave IN (
    'palta_48', 'palta_50', 'palta_48_50', 'palta_60', 'palta_70', 'palta_84'
);
DELETE FROM ext.stock_dashboard_producto
WHERE clave IN ('palta_48', 'palta_50');

INSERT INTO ext.stock_dashboard_producto
    (clave, codigo_representativo, etiqueta, orden, unidad)
VALUES
    ('arandanos',           '890501', 'Arandanos',             10, 'cajas'),
    ('banana_brasil',       '010101', 'Banana Brasil',         20, 'cajas'),
    ('banana_brasil_fibra', '010102', 'Banana Brasil fibra',   30, 'cajas'),
    ('banana_paraguay',     '010401', 'Banana Paraguay',       40, 'cajas'),
    ('banana_bolivia',      '010703', 'Banana Bolivia',        50, 'cajas'),
    ('banana_ecuador',      '010702', 'Banana Ecuador',        60, 'cajas'),
    ('kaki',                 '951401', 'Kaki',                  70, 'cajas'),
    ('choclo',               '030100', 'Choclo',                80, 'cajas'),
    ('ciruela',              '961401', 'Ciruela',               90, 'cajas'),
    ('coco',                 '750101', 'Coco',                 100, 'cajas'),
    ('curcuma',              '090904', 'Curcuma',              110, 'cajas'),
    ('jengibre',             '090901', 'Jengibre',             120, 'cajas'),
    ('kiwi',                 '0802231','Kiwi',                 130, 'cajas'),
    ('lima',                 '111201', 'Lima',                 140, 'cajas'),
    ('mani',                 '970101', 'Mani tostado',         150, 'cajas'),
    ('mango',                '900103', 'Mango',                160, 'cajas'),
    ('melon_valenciano',     '940104', 'Melon Valenciano',     170, 'cajas'),
    ('palta_48_50',          '600106/600107', 'Palta Cal. 48/50', 180, 'cajas'),
    ('palta_60',             '600101', 'Palta Cal. 60',        200, 'cajas'),
    ('palta_70',             '600103', 'Palta Cal. 70',        210, 'cajas'),
    ('palta_84',             '600104', 'Palta Cal. 84',        220, 'cajas'),
    ('papaya_formosa',       '250101', 'Papaya Formosa',       230, 'cajas'),
    ('pina',                 '120706', 'Pina',                 240, 'cajas'),
    ('platano',              '760704', 'Platano',              250, 'cajas'),
    ('pomelo',               '311208', 'Pomelo',               260, 'cajas'),
    ('sandia',               '980101', 'Sandia',               270, 'kg'),
    ('uva_blanca',           '270101', 'Uva blanca',           280, 'cajas'),
    ('uva_negra',            '270102', 'Uva negra',            290, 'cajas'),
    ('uva_rosada',           '270207', 'Uva rosada',           300, 'cajas')
ON CONFLICT (clave) DO UPDATE SET
    codigo_representativo = EXCLUDED.codigo_representativo,
    etiqueta = EXCLUDED.etiqueta,
    orden = EXCLUDED.orden,
    unidad = EXCLUDED.unidad,
    actualizado_en = now();

-- Familias estables del informe de Macrosoft.
INSERT INTO ext.stock_dashboard_producto_regla
    (producto_clave, tipo, valor, prioridad)
VALUES
    ('arandanos',           'cod_stock', '1.1.1.89', 100),
    ('banana_brasil',       'cod_stock', '1.1.1.01', 100),
    ('banana_brasil_fibra', 'cod_stock', '1.1.1.02', 100),
    ('banana_paraguay',     'cod_stock', '1.1.1.04', 100),
    ('banana_bolivia',      'cod_stock', '1.1.1.06', 100),
    ('banana_ecuador',      'cod_stock', '1.1.1.03', 100),
    ('kaki',                 'cod_stock', '1.1.1.95', 100),
    ('choclo',               'cod_stock', '1.1.2.03', 100),
    ('ciruela',              'cod_stock', '1.1.1.96', 100),
    ('coco',                 'cod_stock', '1.1.1.75', 100),
    ('curcuma',              'cod_stock', '1.1.1.07', 100),
    ('jengibre',             'cod_stock', '1.1.1.09', 100),
    ('kiwi',                 'cod_stock', '1.1.1.08', 100),
    ('lima',                 'cod_stock', '1.1.1.15', 100),
    ('mani',                 'cod_stock', '1.1.2.97', 100),
    ('mango',                'cod_stock', '1.1.1.90', 100),
    ('melon_valenciano',     'cod_stock', '1.1.1.13', 100),
    ('papaya_formosa',       'cod_stock', '1.1.1.25', 100),
    ('pina',                 'cod_stock', '1.1.1.12', 100),
    ('platano',              'cod_stock', '1.1.1.76', 100),
    ('pomelo',               'cod_stock', '1.1.1.31', 100),
    ('sandia',               'cod_stock', '1.1.1.98', 100)
ON CONFLICT (producto_clave, tipo, valor) DO NOTHING;

-- Palta: el reporte totaliza 48+50 en una sola presentación y deja el resto de
-- CodStock 60 como calibre 60. La fila combinada evita duplicar ese sistema.
INSERT INTO ext.stock_dashboard_producto_regla
    (producto_clave, tipo, valor, prioridad)
VALUES
    ('palta_48_50', 'descripcion_regex', E'\\bpalta\\b.*(?:cal(?:ibre)?[.]?\\s*)?(?:48|50)\\b', 10),
    ('palta_48_50', 'cod_stock', '1.1.2.59', 20),
    ('palta_70', 'cod_stock', '1.1.2.61', 20),
    ('palta_84', 'cod_stock', '1.1.2.62', 20),
    ('palta_60', 'cod_stock', '1.1.2.60', 100),
    ('palta_60', 'cod_art', '600248', 100)
ON CONFLICT (producto_clave, tipo, valor) DO NOTHING;

-- Uva comparte CodStock; el color se conserva por descripción.
INSERT INTO ext.stock_dashboard_producto_regla
    (producto_clave, tipo, valor, prioridad)
VALUES
    ('uva_blanca', 'descripcion_regex', E'\\buva\\b.*\\bblanc', 10),
    ('uva_negra',  'descripcion_regex', E'\\buva\\b.*\\bnegr', 10),
    ('uva_rosada', 'descripcion_regex', E'\\buva\\b.*\\b(?:rosad|roj)', 10)
ON CONFLICT (producto_clave, tipo, valor) DO NOTHING;
