-- ============================================================================
-- ESQUEMA BASE — Plan de Cargas + Pie de Camión (PostgreSQL, schema `ext`)
--
-- Extracto de pg_migrations/0001_init_ext.sql del ERP Almar (Aloha), recortado
-- a las tablas de IMPORTACIÓN / RECEPCIÓN DE CAMIONES. Se incluyen también
-- `defecto_motivo`, `reclamo` y `reclamo_linea` porque el Pie de Camión las
-- referencia (un pie con defectos genera un reclamo al proveedor).
--
-- Después de este archivo van las migraciones incrementales de
-- sql/pg_migrations/ en orden numérico (agregan columnas y tablas nuevas).
-- ============================================================================


CREATE TABLE IF NOT EXISTS ext.defecto_motivo (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_defecto_motivo_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS ext.reclamo (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(10) NULL,
    nro_fact INT NULL,
    pie_camion_id INT NULL,  -- sin FK (igual que SQL Server; evita ciclo con pie_de_camion)
    generado_por_usuario_id INT NOT NULL,
    generado_en TIMESTAMP NOT NULL DEFAULT now(),
    observaciones VARCHAR(500) NULL,
    pdf_filename VARCHAR(200) NOT NULL,
    pdf_blob BYTEA NOT NULL,
    pdf_size_bytes INT NOT NULL,
    CONSTRAINT fk_reclamo_usuario
        FOREIGN KEY (generado_por_usuario_id) REFERENCES ext.usuarios(id)
);
CREATE INDEX IF NOT EXISTS ix_reclamo_movimiento ON ext.reclamo(documento, nro_fact);

CREATE TABLE IF NOT EXISTS ext.reclamo_linea (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reclamo_id INT NOT NULL,
    cod_art VARCHAR(30) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    cantidad_defectuosa NUMERIC(10,3) NOT NULL,
    motivo_id INT NOT NULL,
    notas VARCHAR(500) NULL,
    cantidad_fotos INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_reclamo_linea_reclamo
        FOREIGN KEY (reclamo_id) REFERENCES ext.reclamo(id) ON DELETE CASCADE,
    CONSTRAINT fk_reclamo_linea_motivo
        FOREIGN KEY (motivo_id) REFERENCES ext.defecto_motivo(id)
);

-- ── Plan de Cargas (BR/PY) ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ext.plan_de_cargas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    carga_semana VARCHAR(20) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Solicitado',
    factura VARCHAR(30) NULL,
    productor VARCHAR(100) NULL,
    fecha_carga DATE NULL,
    carpeta_import VARCHAR(40) NULL,
    afidi VARCHAR(300) NULL,

    transportista VARCHAR(100) NULL,
    exportador VARCHAR(150) NULL,
    placa_camion VARCHAR(30) NULL,
    placa_remolque VARCHAR(30) NULL,
    chofer VARCHAR(100) NULL,
    celular VARCHAR(40) NULL,

    fecha_frontera DATE NULL,
    frontera VARCHAR(50) NULL,
    inspector_mgap VARCHAR(100) NULL,
    fecha_descarga DATE NULL,

    tt INT NULL,
    cajas_mic INT NULL,
    cajas_desc INT NULL,
    cant_pallet INT NULL,
    cant_kilos_caja DOUBLE PRECISION NULL,
    codigo_viaje VARCHAR(40) NULL,
    mic VARCHAR(40) NULL,

    observaciones TEXT NULL,

    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
    creado_por_usuario_id INT NULL,
    actualizado_por_usuario_id INT NULL,

    CONSTRAINT fk_plan_de_cargas_creado_por
        FOREIGN KEY (creado_por_usuario_id) REFERENCES ext.usuarios(id),
    CONSTRAINT fk_plan_de_cargas_actualizado_por
        FOREIGN KEY (actualizado_por_usuario_id) REFERENCES ext.usuarios(id)
);
CREATE INDEX IF NOT EXISTS ix_plan_de_cargas_status ON ext.plan_de_cargas(status);
CREATE INDEX IF NOT EXISTS ix_plan_de_cargas_fecha_descarga ON ext.plan_de_cargas(fecha_descarga);
CREATE INDEX IF NOT EXISTS ix_plan_de_cargas_fecha_frontera ON ext.plan_de_cargas(fecha_frontera);

-- ── Pie de Camión ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ext.pie_de_camion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora_inicio VARCHAR(5) NULL,        -- "HH:MM"
    hora_fin VARCHAR(5) NULL,

    chofer_nombre VARCHAR(100) NOT NULL,
    placa_camion VARCHAR(20) NOT NULL,

    -- deprecated: el front nuevo escribe marca por línea
    producto VARCHAR(100) NULL,
    marca VARCHAR(100) NULL,

    exportador VARCHAR(150) NULL,
    empresa_transporte VARCHAR(150) NULL,
    numero_afidi VARCHAR(50) NULL,
    codigo_importador_camion VARCHAR(30) NULL,

    intervenido_agronomia BOOLEAN NOT NULL DEFAULT false,
    inspector_agronomo VARCHAR(100) NULL,

    -- Condiciones generales (1-5 + comentario)
    palet_rating SMALLINT NULL,
    palet_comentario VARCHAR(200) NULL,
    cajas_rating SMALLINT NULL,
    cajas_comentario VARCHAR(200) NULL,
    flejes_rating SMALLINT NULL,
    flejes_comentario VARCHAR(200) NULL,

    -- Mediciones (Puerta / Medio / Atrás, 2 valores cada uno)
    temp_pulpa_puerta_1 NUMERIC(5,2) NULL,
    temp_pulpa_puerta_2 NUMERIC(5,2) NULL,
    temp_pulpa_medio_1 NUMERIC(5,2) NULL,
    temp_pulpa_medio_2 NUMERIC(5,2) NULL,
    temp_pulpa_atras_1 NUMERIC(5,2) NULL,
    temp_pulpa_atras_2 NUMERIC(5,2) NULL,

    peso_caja_puerta_1 NUMERIC(5,2) NULL,
    peso_caja_puerta_2 NUMERIC(5,2) NULL,
    peso_caja_medio_1 NUMERIC(5,2) NULL,
    peso_caja_medio_2 NUMERIC(5,2) NULL,
    peso_caja_atras_1 NUMERIC(5,2) NULL,
    peso_caja_atras_2 NUMERIC(5,2) NULL,

    calibracion_puerta INT NULL,
    calibracion_medio INT NULL,
    calibracion_atras INT NULL,

    longitud_puerta NUMERIC(5,2) NULL,
    longitud_medio NUMERIC(5,2) NULL,
    longitud_atras NUMERIC(5,2) NULL,
    longitud_unidad VARCHAR(10) NOT NULL DEFAULT 'cm',

    -- Regular / Buena / Muy buena
    corona VARCHAR(20) NULL,
    quemada VARCHAR(20) NULL,
    rameada VARCHAR(20) NULL,

    descarga_autorizada_por VARCHAR(100) NULL,
    inspeccion_realizada_por VARCHAR(100) NULL,

    total_cajas INT NULL,
    observaciones VARCHAR(500) NULL,

    pdf_filename VARCHAR(200) NOT NULL,
    pdf_blob BYTEA NOT NULL,
    pdf_size_bytes INT NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    ingreso_documento VARCHAR(10) NULL,
    ingreso_nro_fact INT NULL,
    confirmado_por_usuario_id INT NULL,
    confirmado_en TIMESTAMP NULL,
    reclamo_id INT NULL,
    plan_carga_id INT NULL,

    creado_por_usuario_id INT NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_pie_de_camion_usuario
        FOREIGN KEY (creado_por_usuario_id) REFERENCES ext.usuarios(id),
    CONSTRAINT fk_pie_de_camion_confirmado
        FOREIGN KEY (confirmado_por_usuario_id) REFERENCES ext.usuarios(id),
    CONSTRAINT fk_pie_de_camion_reclamo
        FOREIGN KEY (reclamo_id) REFERENCES ext.reclamo(id),
    CONSTRAINT fk_pie_de_camion_plan_de_cargas
        FOREIGN KEY (plan_carga_id) REFERENCES ext.plan_de_cargas(id)
);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_fecha ON ext.pie_de_camion(fecha DESC);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_plan_carga ON ext.pie_de_camion(plan_carga_id);

CREATE TABLE IF NOT EXISTS ext.pie_de_camion_linea (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pie_camion_id INT NOT NULL,
    cod_art VARCHAR(30) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    deposito VARCHAR(4) NOT NULL,
    cantidad NUMERIC(10,3) NOT NULL,
    marca VARCHAR(100) NULL,
    orden INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pie_de_camion_linea_pie
        FOREIGN KEY (pie_camion_id) REFERENCES ext.pie_de_camion(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_linea_pie ON ext.pie_de_camion_linea(pie_camion_id);

-- deprecated (el front nuevo usa marca por línea); queda por compat con data vieja
CREATE TABLE IF NOT EXISTS ext.pie_de_camion_producto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pie_camion_id INT NOT NULL,
    producto VARCHAR(100) NOT NULL,
    marca VARCHAR(100) NULL,
    orden INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pie_de_camion_producto_pie
        FOREIGN KEY (pie_camion_id) REFERENCES ext.pie_de_camion(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_producto_pie ON ext.pie_de_camion_producto(pie_camion_id);

CREATE TABLE IF NOT EXISTS ext.pie_de_camion_defecto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pie_camion_linea_id INT NOT NULL,
    motivo_id INT NOT NULL,
    cantidad NUMERIC(10,3) NOT NULL,
    notas VARCHAR(500) NULL,
    cantidad_fotos INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pie_de_camion_defecto_linea
        FOREIGN KEY (pie_camion_linea_id) REFERENCES ext.pie_de_camion_linea(id) ON DELETE CASCADE,
    CONSTRAINT fk_pie_de_camion_defecto_motivo
        FOREIGN KEY (motivo_id) REFERENCES ext.defecto_motivo(id)
);

CREATE TABLE IF NOT EXISTS ext.pie_de_camion_foto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pie_camion_id INT NOT NULL,
    foto_blob BYTEA NOT NULL,
    mime_type VARCHAR(50) NOT NULL DEFAULT 'image/jpeg',
    size_bytes INT NOT NULL,
    orden INT NOT NULL DEFAULT 0,
    caption VARCHAR(200) NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_pie_de_camion_foto_pie
        FOREIGN KEY (pie_camion_id) REFERENCES ext.pie_de_camion(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_pie_de_camion_foto_pie ON ext.pie_de_camion_foto(pie_camion_id);
